"""
src/models/blocks.py
====================

Reusable PyTorch building blocks for the anomaly-detection architectures
generated by ``src.models.model_factory``. Every block in this module is
designed to be:

- *Quantization-friendly*: no in-place ops on residual paths, no
  `ConvTranspose2d` in the default upsample path, BN foldable into a
  preceding `Conv2d`.
- *TensorRT-friendly*: bilinear upsample, fixed scale factors, no
  Python control flow inside ``forward``.
- *Genome-friendly*: a single normalized config (``norm`` / ``activation``
  / ``kernel_size`` / ...) drives every block, so an NSGA-II encoder can
  flip layer types without bespoke wiring.

Layer catalogue
---------------
- :class:`ConvBNAct`             – Conv2d → Norm → Activation.
- :class:`DepthwiseSeparableConv` – Depthwise + Pointwise (MobileNetV1).
- :class:`InvertedResidual`      – MobileNetV2 inverted-residual block.
- :class:`ResidualBlock`         – ResNet-style basic / bottleneck block.
- :class:`SEBlock`               – Squeeze-and-Excitation channel attention.
- :class:`ECABlock`              – Efficient Channel Attention (1-D conv).
- :class:`SpatialAttention`      – Mean+Max pool → 7×7 conv → sigmoid.
- :class:`CBAMLite`              – SE + SpatialAttention (sequential).
- :class:`UpsampleConv`          – Bilinear upsample + Conv refinement.
- :class:`PixelShuffleUp`        – Sub-pixel convolution upsample.
- :class:`ConvTransposeUp`       – Transposed-conv upsample (fallback).

Helper builders
---------------
- :func:`make_norm`        – Build a 2-D normalization layer by name.
- :func:`make_activation`  – Build an activation by name.
- :func:`make_conv_block`  – Dispatch ``conv | ds | ir`` block flavors.
- :func:`make_attention`   – Dispatch ``se | eca | spatial | cbam | none``.

All blocks accept ``in_channels``/``out_channels`` and the relevant
hyperparameters as plain ``int``/``str`` arguments — no nested config
dicts — so they're trivial to compose programmatically.
"""

from __future__ import annotations

from typing import Literal

import torch
import torch.nn as nn
import torch.nn.functional as F

__all__ = [
    "make_norm",
    "make_activation",
    "make_conv_block",
    "make_attention",
    "ConvBNAct",
    "DepthwiseSeparableConv",
    "InvertedResidual",
    "ResidualBlock",
    "SEBlock",
    "ECABlock",
    "SpatialAttention",
    "CBAMLite",
    "UpsampleConv",
    "PixelShuffleUp",
    "ConvTransposeUp",
]

NormKind = Literal["batch", "instance", "group", "none"]
ActKind = Literal["relu", "leaky_relu", "gelu", "silu", "hardswish", "none"]
ConvKind = Literal["conv", "ds", "ir"]
AttnKind = Literal["se", "eca", "spatial", "cbam", "none"]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def make_norm(channels: int, kind: NormKind = "batch") -> nn.Module:
    """Instantiate a 2-D normalization layer by name.

    ``"group"`` picks an automatic group count of ``min(32, channels // 4)``
    that always divides ``channels``.
    """
    if kind == "batch":
        return nn.BatchNorm2d(channels)
    if kind == "instance":
        return nn.InstanceNorm2d(channels, affine=True)
    if kind == "group":
        groups = max(1, min(32, channels // 4))
        # Ensure groups divides channels.
        while channels % groups != 0 and groups > 1:
            groups -= 1
        return nn.GroupNorm(groups, channels)
    if kind == "none":
        return nn.Identity()
    raise ValueError(f"unknown norm: {kind!r}")


def make_activation(kind: ActKind = "relu",
                    inplace: bool = False) -> nn.Module:
    """Instantiate an activation by name.

    ``inplace`` is only honored for activations that support it; it is
    *off by default* because in-place activations can break residual
    paths during backprop and confuse some quantization backends.
    """
    if kind == "relu":
        return nn.ReLU(inplace=inplace)
    if kind == "leaky_relu":
        return nn.LeakyReLU(0.1, inplace=inplace)
    if kind == "gelu":
        return nn.GELU()
    if kind == "silu":
        return nn.SiLU(inplace=inplace)
    if kind == "hardswish":
        return nn.Hardswish(inplace=inplace)
    if kind == "none":
        return nn.Identity()
    raise ValueError(f"unknown activation: {kind!r}")


def _check_kernel(kernel_size: int) -> int:
    if kernel_size < 1 or kernel_size % 2 == 0:
        raise ValueError(f"kernel_size must be a positive odd int; "
                         f"got {kernel_size}")
    return kernel_size


# ---------------------------------------------------------------------------
# Convolutional blocks
# ---------------------------------------------------------------------------
class ConvBNAct(nn.Module):
    """Conv2d → Norm → Activation.

    Bias is automatically disabled when a normalization layer is used
    (BN/IN/GN folds away the constant), and re-enabled when ``norm="none"``.
    """

    def __init__(self,
                 in_channels: int,
                 out_channels: int,
                 kernel_size: int = 3,
                 stride: int = 1,
                 groups: int = 1,
                 dilation: int = 1,
                 norm: NormKind = "batch",
                 activation: ActKind = "relu",
                 use_act: bool = True,
                 padding_mode: str = "zeros") -> None:
        super().__init__()
        _check_kernel(kernel_size)
        pad = (kernel_size // 2) * dilation
        self.conv = nn.Conv2d(in_channels, out_channels,
                              kernel_size=kernel_size, stride=stride,
                              padding=pad, dilation=dilation, groups=groups,
                              bias=(norm == "none"),
                              padding_mode=padding_mode)
        self.norm = make_norm(out_channels, norm)
        self.act = make_activation(activation) if use_act else nn.Identity()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.act(self.norm(self.conv(x)))


class DepthwiseSeparableConv(nn.Module):
    """Depthwise (groups=in_ch) followed by 1×1 pointwise conv.

    A residual shortcut is added automatically when ``in_channels ==
    out_channels`` and ``stride == 1`` (controllable via ``residual``).
    """

    def __init__(self,
                 in_channels: int,
                 out_channels: int,
                 kernel_size: int = 3,
                 stride: int = 1,
                 norm: NormKind = "batch",
                 activation: ActKind = "relu",
                 residual: bool | None = None) -> None:
        super().__init__()
        self.dw = ConvBNAct(in_channels, in_channels,
                            kernel_size=kernel_size, stride=stride,
                            groups=in_channels, norm=norm,
                            activation=activation)
        self.pw = ConvBNAct(in_channels, out_channels,
                            kernel_size=1, stride=1,
                            norm=norm, activation=activation)
        if residual is None:
            residual = (stride == 1 and in_channels == out_channels)
        self.use_residual = residual

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        out = self.pw(self.dw(x))
        return out + x if self.use_residual else out


class InvertedResidual(nn.Module):
    """MobileNetV2 inverted-residual block.

    Pipeline: 1×1 expand → k×k depthwise → 1×1 project (no activation).
    Adds a skip connection when ``stride == 1`` and channels match.
    """

    def __init__(self,
                 in_channels: int,
                 out_channels: int,
                 kernel_size: int = 3,
                 stride: int = 1,
                 expansion: int = 4,
                 norm: NormKind = "batch",
                 activation: ActKind = "relu") -> None:
        super().__init__()
        if expansion < 1:
            raise ValueError(f"expansion must be >= 1; got {expansion}")
        hidden = max(in_channels * expansion, 8)
        self.use_skip = (stride == 1 and in_channels == out_channels)

        layers: list[nn.Module] = []
        if expansion != 1:
            layers.append(ConvBNAct(in_channels, hidden, kernel_size=1,
                                    stride=1, norm=norm,
                                    activation=activation))
        layers += [
            ConvBNAct(hidden, hidden, kernel_size=kernel_size,
                      stride=stride, groups=hidden, norm=norm,
                      activation=activation),
            ConvBNAct(hidden, out_channels, kernel_size=1, stride=1,
                      norm=norm, activation=activation, use_act=False),
        ]
        self.block = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        out = self.block(x)
        return out + x if self.use_skip else out


class ResidualBlock(nn.Module):
    """ResNet-style residual block (basic or bottleneck).

    - ``bottleneck=False``: 3×3 → 3×3, identity / 1×1 shortcut.
    - ``bottleneck=True``:  1×1 reduce → 3×3 → 1×1 expand (×4), identity /
      1×1 shortcut. Channel-reduction factor is fixed at 4 (ResNet
      convention); override via ``bottleneck_ratio`` if needed.
    """

    def __init__(self,
                 in_channels: int,
                 out_channels: int,
                 kernel_size: int = 3,
                 stride: int = 1,
                 norm: NormKind = "batch",
                 activation: ActKind = "relu",
                 bottleneck: bool = False,
                 bottleneck_ratio: int = 4) -> None:
        super().__init__()
        _check_kernel(kernel_size)
        self.act_out = make_activation(activation)

        if bottleneck:
            mid = max(out_channels // bottleneck_ratio, 8)
            self.conv = nn.Sequential(
                ConvBNAct(in_channels, mid, kernel_size=1, stride=1,
                          norm=norm, activation=activation),
                ConvBNAct(mid, mid, kernel_size=kernel_size, stride=stride,
                          norm=norm, activation=activation),
                ConvBNAct(mid, out_channels, kernel_size=1, stride=1,
                          norm=norm, activation=activation, use_act=False),
            )
        else:
            self.conv = nn.Sequential(
                ConvBNAct(in_channels, out_channels,
                          kernel_size=kernel_size, stride=stride,
                          norm=norm, activation=activation),
                ConvBNAct(out_channels, out_channels,
                          kernel_size=kernel_size, stride=1,
                          norm=norm, activation=activation, use_act=False),
            )

        if stride == 1 and in_channels == out_channels:
            self.shortcut: nn.Module = nn.Identity()
        else:
            # Projection shortcut keeps spatial / channel alignment.
            self.shortcut = ConvBNAct(in_channels, out_channels,
                                       kernel_size=1, stride=stride,
                                       norm=norm, activation=activation,
                                       use_act=False)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.act_out(self.conv(x) + self.shortcut(x))


# ---------------------------------------------------------------------------
# Attention-lite blocks
# ---------------------------------------------------------------------------
class SEBlock(nn.Module):
    """Squeeze-and-Excitation channel attention (Hu et al., 2018).

    Implemented with 1×1 convolutions instead of FC layers for a
    spatial-size-agnostic, quantization-friendly graph.
    """

    def __init__(self,
                 channels: int,
                 reduction: int = 16,
                 activation: ActKind = "relu") -> None:
        super().__init__()
        hidden = max(channels // max(reduction, 1), 4)
        self.pool = nn.AdaptiveAvgPool2d(1)
        self.fc1 = nn.Conv2d(channels, hidden, kernel_size=1, bias=True)
        self.act = make_activation(activation)
        self.fc2 = nn.Conv2d(hidden, channels, kernel_size=1, bias=True)
        self.gate = nn.Sigmoid()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        s = self.pool(x)
        s = self.act(self.fc1(s))
        s = self.gate(self.fc2(s))
        return x * s


class ECABlock(nn.Module):
    """Efficient Channel Attention (Wang et al., 2020).

    A single 1-D convolution along the channel dimension replaces the
    SE block's two FC layers — ~0 extra parameters and lower latency.
    """

    def __init__(self, channels: int, kernel_size: int = 3) -> None:
        super().__init__()
        _check_kernel(kernel_size)
        self.pool = nn.AdaptiveAvgPool2d(1)
        self.conv = nn.Conv1d(1, 1, kernel_size=kernel_size,
                              padding=kernel_size // 2, bias=False)
        self.gate = nn.Sigmoid()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        b, c, _, _ = x.shape
        s = self.pool(x).view(b, 1, c)        # [B, 1, C]
        s = self.conv(s)
        s = self.gate(s).view(b, c, 1, 1)
        return x * s


class SpatialAttention(nn.Module):
    """Lightweight spatial attention (CBAM-style spatial path).

    Concats per-channel mean and max maps, applies a single 7×7
    convolution, gates with sigmoid, multiplies the input.
    """

    def __init__(self, kernel_size: int = 7) -> None:
        super().__init__()
        _check_kernel(kernel_size)
        self.conv = nn.Conv2d(2, 1, kernel_size=kernel_size,
                              padding=kernel_size // 2, bias=False)
        self.gate = nn.Sigmoid()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        avg = x.mean(dim=1, keepdim=True)
        mx = x.amax(dim=1, keepdim=True)
        s = self.gate(self.conv(torch.cat([avg, mx], dim=1)))
        return x * s


class CBAMLite(nn.Module):
    """Channel attention (SE) followed by spatial attention.

    Lighter than full CBAM (no max-pool branch on the channel side),
    suitable for embedded targets while still capturing both
    inter-channel and inter-spatial dependencies.
    """

    def __init__(self,
                 channels: int,
                 reduction: int = 16,
                 spatial_kernel: int = 7,
                 channel_attn: Literal["se", "eca"] = "se",
                 activation: ActKind = "relu") -> None:
        super().__init__()
        if channel_attn == "se":
            self.channel = SEBlock(channels, reduction=reduction,
                                   activation=activation)
        else:
            self.channel = ECABlock(channels)
        self.spatial = SpatialAttention(kernel_size=spatial_kernel)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.spatial(self.channel(x))


# ---------------------------------------------------------------------------
# Upsampling blocks
# ---------------------------------------------------------------------------
class UpsampleConv(nn.Module):
    """Bilinear upsample (×scale) followed by a convolutional refinement.

    The bilinear-then-conv pattern is preferred over ``ConvTranspose2d``
    because it avoids checkerboard artifacts and is cleanly representable
    in TensorRT with PTQ/QAT.
    """

    def __init__(self,
                 in_channels: int,
                 out_channels: int,
                 *,
                 scale_factor: float = 2.0,
                 kernel_size: int = 3,
                 norm: NormKind = "batch",
                 activation: ActKind = "relu",
                 mode: Literal["bilinear", "nearest"] = "bilinear",
                 align_corners: bool = False) -> None:
        super().__init__()
        self.scale_factor = float(scale_factor)
        self.mode = mode
        self.align_corners = align_corners if mode == "bilinear" else None
        self.refine = ConvBNAct(in_channels, out_channels,
                                kernel_size=kernel_size, stride=1,
                                norm=norm, activation=activation)

    def forward(self,
                x: torch.Tensor,
                size: tuple[int, int] | None = None) -> torch.Tensor:
        if size is not None:
            x = F.interpolate(x, size=size, mode=self.mode,
                              align_corners=self.align_corners)
        else:
            x = F.interpolate(x, scale_factor=self.scale_factor,
                              mode=self.mode,
                              align_corners=self.align_corners)
        return self.refine(x)


class PixelShuffleUp(nn.Module):
    """Sub-pixel convolution upsampling (Shi et al., 2016).

    Produces sharper edges than bilinear+conv but at a higher parameter
    cost (the conv expands to ``out_channels * upscale_factor**2``).
    """

    def __init__(self,
                 in_channels: int,
                 out_channels: int,
                 *,
                 upscale_factor: int = 2,
                 kernel_size: int = 3,
                 norm: NormKind = "batch",
                 activation: ActKind = "relu") -> None:
        super().__init__()
        if upscale_factor < 1:
            raise ValueError("upscale_factor must be >= 1")
        self.expand = ConvBNAct(
            in_channels,
            out_channels * (upscale_factor ** 2),
            kernel_size=kernel_size, stride=1,
            norm=norm, activation=activation, use_act=False,
        )
        self.shuffle = nn.PixelShuffle(upscale_factor)
        self.act = make_activation(activation)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.act(self.shuffle(self.expand(x)))


class ConvTransposeUp(nn.Module):
    """Transposed convolution upsampling (legacy / fallback).

    Less quantization-friendly than :class:`UpsampleConv`; kept for
    explicit comparisons in the NAS search space.
    """

    def __init__(self,
                 in_channels: int,
                 out_channels: int,
                 *,
                 stride: int = 2,
                 kernel_size: int = 4,
                 norm: NormKind = "batch",
                 activation: ActKind = "relu") -> None:
        super().__init__()
        if kernel_size <= 0:
            raise ValueError("kernel_size must be > 0")
        self.deconv = nn.ConvTranspose2d(
            in_channels, out_channels,
            kernel_size=kernel_size, stride=stride,
            padding=max((kernel_size - stride) // 2, 0),
            bias=(norm == "none"),
        )
        self.norm = make_norm(out_channels, norm)
        self.act = make_activation(activation)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.act(self.norm(self.deconv(x)))


# ---------------------------------------------------------------------------
# Dispatchers (handy for genome-driven model assembly)
# ---------------------------------------------------------------------------
def make_conv_block(in_channels: int,
                    out_channels: int,
                    *,
                    kind: ConvKind = "conv",
                    kernel_size: int = 3,
                    stride: int = 1,
                    norm: NormKind = "batch",
                    activation: ActKind = "relu",
                    expansion: int = 4) -> nn.Module:
    """Build a convolutional stage by name.

    ``kind`` ∈ ``{"conv", "ds", "ir"}`` selects, respectively,
    :class:`ConvBNAct`, :class:`DepthwiseSeparableConv`, and
    :class:`InvertedResidual`. The remaining kwargs cover the union of
    constructor signatures.
    """
    if kind == "conv":
        return ConvBNAct(in_channels, out_channels,
                         kernel_size=kernel_size, stride=stride,
                         norm=norm, activation=activation)
    if kind == "ds":
        return DepthwiseSeparableConv(in_channels, out_channels,
                                      kernel_size=kernel_size, stride=stride,
                                      norm=norm, activation=activation)
    if kind == "ir":
        return InvertedResidual(in_channels, out_channels,
                                kernel_size=kernel_size, stride=stride,
                                expansion=expansion, norm=norm,
                                activation=activation)
    raise ValueError(f"unknown conv kind: {kind!r}")


def make_attention(channels: int,
                   *,
                   kind: AttnKind = "none",
                   reduction: int = 16,
                   spatial_kernel: int = 7,
                   activation: ActKind = "relu") -> nn.Module:
    """Build an attention module by name.

    ``kind`` ∈ ``{"se", "eca", "spatial", "cbam", "none"}``. ``"none"``
    returns ``nn.Identity()`` so the call site can stay branch-free.
    """
    if kind == "se":
        return SEBlock(channels, reduction=reduction, activation=activation)
    if kind == "eca":
        return ECABlock(channels)
    if kind == "spatial":
        return SpatialAttention(kernel_size=spatial_kernel)
    if kind == "cbam":
        return CBAMLite(channels, reduction=reduction,
                        spatial_kernel=spatial_kernel,
                        activation=activation)
    if kind == "none":
        return nn.Identity()
    raise ValueError(f"unknown attention kind: {kind!r}")
